#!/usr/bin/env python3
"""Resolve highlight-query inheritance and emit bounded C string tables."""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path


LANGUAGES = (
    "c", "cpp", "rust", "go", "python", "javascript", "typescript",
    "tsx", "bash", "json", "toml", "yaml",
)
INHERITS = re.compile(r"^;\s*inherits\s*:\s*(.+?)\s*$", re.MULTILINE)
# The TypeScript repository ships only its additions; consumers combine them
# with the JavaScript query even though the file has no Neovim-style directive.
BASES = {"typescript": ("javascript",), "tsx": ("javascript",)}


def resolve(root: Path, name: str, stack: tuple[str, ...] = ()) -> bytes:
    if name in stack:
        raise SystemExit(f"query inheritance cycle: {' -> '.join((*stack, name))}")
    path = root / "grammars" / name / "highlights.scm"
    try:
        text = path.read_text()
    except OSError as exc:
        raise SystemExit(f"cannot read {path}: {exc}") from exc
    inherited: list[str] = []
    for match in INHERITS.finditer(text):
        inherited.extend(part.strip() for part in match.group(1).split(","))
    text = INHERITS.sub("", text)
    parents = [*BASES.get(name, ()), *inherited]
    chunks = [resolve(root, parent, (*stack, name)) for parent in parents]
    chunks.append(text.encode())
    query = b"\n".join(chunks)
    if b"@" not in query:
        raise SystemExit(f"{name}: highlight query has no captures")
    return query


def c_bytes(data: bytes) -> str:
    out = []
    for start in range(0, len(data), 16):
        chunk = data[start : start + 16]
        out.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return "\n".join(out)


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: embed-highlights.py VENDOR_ROOT OUTPUT", file=sys.stderr)
        return 2
    root = Path(sys.argv[1])
    output = Path(sys.argv[2])
    parts = [
        "/* Generated by scripts/embed-highlights.py. */\n",
        '#include "queries.h"\n\n',
    ]
    entries = []
    for name in LANGUAGES:
        query = resolve(root, name)
        ident = name.replace("-", "_")
        parts.append(f"static const unsigned char query_{ident}[] = {{\n")
        parts.append(c_bytes(query))
        parts.append("\n};\n\n")
        digest = hashlib.sha256(query).hexdigest()
        entries.append((name, ident, len(query), digest))
    parts.append("const YhlQuerySource yhl_query_sources[] = {\n")
    for name, ident, size, digest in entries:
        parts.append(
            f'    {{ "{name}", query_{ident}, {size}u, "{digest}" }},\n'
        )
    parts.append("};\n")
    parts.append(
        "const size_t yhl_query_source_count = "
        "sizeof yhl_query_sources / sizeof yhl_query_sources[0];\n"
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("".join(parts))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
