#!/usr/bin/env python3
"""Generate src/width.c: the terminal column width of every code point.

The width of a glyph decides where every cell after it lands, so it has to be
the same answer on every machine. The C library is not that answer: glibc and
musl carry different Unicode versions, and glibc's own tables move between
releases, so the identical transcript frames differently depending on where
the binary runs and against what it was linked.

The rules are Markus Kuhn's, the ones every wcwidth follows:

  * NUL is zero, and the C0 and C1 controls have no width at all.
  * Nonspacing and enclosing marks (Mn, Me) and format characters (Cf)
    combine with the glyph before them and occupy no column of their own.
    The soft hyphen is the exception every implementation makes: terminals
    print it. Hangul conjoining medials and finals compose likewise.
  * East Asian Wide and Fullwidth occupy two columns.
  * Everything else, including code points this Unicode version has not
    assigned, occupies one.

Run it from the repository root; it rewrites src/width.c in place. The Unicode
version is Python's own, and it is recorded in the generated file.
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

MAX_CP = 0x110000
OUT = Path("src/width.c")

# Conjoining Hangul Jamo: a medial or final composes onto the syllable that
# the leading jamo began, so the sequence is one cell wide, not three.
JAMO_MEDIAL_FINAL = range(0x1160, 0x1200)
SOFT_HYPHEN = 0x00AD


def width(cp: int) -> int:
    """Columns for one code point: 0, 1 or 2. Controls are 0."""
    if cp == 0:
        return 0
    if cp < 0x20 or 0x7F <= cp < 0xA0:
        return 0
    if cp in JAMO_MEDIAL_FINAL:
        return 0
    if cp != SOFT_HYPHEN and unicodedata.category(chr(cp)) in ("Mn", "Me", "Cf"):
        return 0
    if unicodedata.east_asian_width(chr(cp)) in ("W", "F"):
        return 2
    return 1


def ranges(want: int) -> list[tuple[int, int]]:
    """Coalesced [lo, hi] spans of the code points of that width."""
    out: list[tuple[int, int]] = []
    for cp in range(MAX_CP):
        if width(cp) != want:
            continue
        if out and out[-1][1] == cp - 1:
            out[-1] = (out[-1][0], cp)
        else:
            out.append((cp, cp))
    return out


def table(name: str, spans: list[tuple[int, int]]) -> str:
    rows = []
    for i in range(0, len(spans), 4):
        chunk = spans[i : i + 4]
        rows.append(
            "    " + " ".join(f"{{0x{lo:04X}, 0x{hi:04X}}}," for lo, hi in chunk)
        )
    body = "\n".join(rows)
    return f"static const WidthRange {name}[] = {{\n{body}\n}};\n"


def main() -> int:
    if not OUT.parent.is_dir():
        raise SystemExit("run from the repository root")
    # The generated lookup answers 1 for everything below U+0300 without
    # consulting a table, which is where the common case exits. Prove the
    # shortcut against this Unicode version rather than trusting it.
    for cp in [*range(0x20, 0x7F), *range(0xA0, 0x0300)]:
        if width(cp) != 1:
            raise SystemExit(f"U+{cp:04X} is not one column; fix the shortcut")
    zero = ranges(0)
    wide = ranges(2)
    text = f'''/* Generated by scripts/gen-width.py from Unicode {unicodedata.unidata_version}.
 * Do not edit: regenerate it.
 *
 * The column width of a code point, decided here rather than by wcwidth().
 * The C library's tables differ between glibc and musl and between glibc
 * releases, and a width that changes with the libc frames the same transcript
 * differently on different machines. Owning the table makes the layout a
 * property of this program. */

#include "agent.h"

typedef struct {{ u32 lo, hi; }} WidthRange;

/* Zero width: NUL, the C0 and C1 controls, nonspacing and enclosing marks,
 * format characters other than the soft hyphen, and conjoining Hangul
 * medials and finals. */
{table("k_zero", zero)}
/* Two columns: East Asian Wide and Fullwidth. */
{table("k_wide", wide)}
static b8 in_ranges(const WidthRange *r, size_t n, u32 cp) {{
    size_t lo = 0, hi = n;
    while (lo < hi) {{
        size_t mid = lo + (hi - lo) / 2;
        if (cp < r[mid].lo) hi = mid;
        else if (cp > r[mid].hi) lo = mid + 1;
        else return true;
    }}
    return false;
}}

i32 agent_width(u32 cp) {{
    if (cp < 0x20u || (cp >= 0x7Fu && cp < 0xA0u)) return 0;
    if (cp < 0x0300u) return 1;   /* ASCII and Latin-1 letters, the common case */
    if (cp > 0x10FFFFu) return 1;
    if (in_ranges(k_zero, sizeof k_zero / sizeof k_zero[0], cp)) return 0;
    if (in_ranges(k_wide, sizeof k_wide / sizeof k_wide[0], cp)) return 2;
    return 1;
}}
'''
    OUT.write_text(text)
    print(
        f"{OUT}: Unicode {unicodedata.unidata_version}, "
        f"{len(zero)} zero-width and {len(wide)} wide ranges"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
