#ifndef AGENT_HIGHLIGHT_PROTOCOL_H
#define AGENT_HIGHLIGHT_PROTOCOL_H

#define YHL_MAGIC           "YHL1"
#define YHL_REQUEST_HEADER  20u
#define YHL_RESPONSE_HEADER 16u
#define YHL_RUN_BYTES       12u

#define YHL_SOURCE_MAX   (64u << 10)
#define YHL_ALIAS_MAX    32u
#define YHL_FILENAME_MAX 4096u
#define YHL_RUN_MAX      16384u

enum {
    YHL_HINT_ALIAS = 1,
    YHL_HINT_FILENAME = 2,
};

enum {
    YHL_STATUS_OK = 0,
    YHL_STATUS_UNKNOWN = 1,
    YHL_STATUS_TOO_LARGE = 2,
    YHL_STATUS_TOO_COMPLEX = 3,
    YHL_STATUS_INTERNAL = 4,
};

enum {
    YHL_SEM_COMMENT = 1,
    YHL_SEM_STRING,
    YHL_SEM_NUMBER,
    YHL_SEM_KEYWORD,
    YHL_SEM_TYPE,
    YHL_SEM_FUNCTION,
    YHL_SEM_BUILTIN,
};

#endif
